apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-data-claim
  namespace: $NS
spec:
  storageClassName: vultr-block-storage 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
