apiVersion: v1
kind: LimitRange
metadata:
  name: default-resource-limits
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: 200m     # 200 millicores (20% of 1 CPU)
      memory: 256Mi # 256 Megabytes
    default:        # This is the Limit!
      cpu: 500m     # 500 millicores (50% of 1 CPU)
      memory: 512Mi # 512 Megabytes
