apiVersion: v1
kind: Pod
metadata:
  name: greedy-database
  namespace: $NS
spec:
  containers:
  - name: db
    image: redis
    resources:
      requests:
        memory: "4Gi"
      limits:
        memory: "4Gi"
